### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow-efolder#640] opened 2017-10-17 16:24 UTC
no implicit conversion of nil into String

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/363/

**Comment by aroltsch** [comment] 2017-11-07 15:29
duplicate of https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/599

**Closed by aroltsch** 2017-11-07 15:29 UTC
Labels: eFolder Express, prod-alert, whiskey
