### ISSUE TITLE
eFolder Express can't sign out

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#990] opened 2018-04-18 14:57 UTC
## Context
Lowell identified the inability to sign out. This was verified in a production environment

## Priority
Medium - high: in production but not a commonly used feature

## Reproduction
Clicking sign out under profile takes you to the home page of eFolder Express

**Comment by lowellrex** [comment] 2018-04-19 11:58
Unable to reproduce locally, but could in UAT.

## Reproduction steps
* Click the "Sign out" link in the top right dropdown menu
* If it works, sign back in (it sometimes works the first time... perhaps after a long-running session?)
* Attempt to sign out again (it should fail)

I suspect this fails in UAT and production because of how single sign-on redirection is working (we handle this a little differently when running locally in `[ApplicationController.authenticate()](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/08d037bee67da8722361748ca1c4acd413de0540/app/controllers/application_controller.rb#L14)`, and probably other places as well).

**Comment by mdbenjam** [comment] 2018-04-20 22:31
Have there been user complaints about this? If not I think it's low priority.

**Comment by Chingujo** [comment] 2018-04-30 15:41
Just one and the use case of eFolder Express is that it stays open through the work period. Additionally, it seems people just x the browser and the low utilization of this section in GA makes me a agree with Mark here. Thanks Mark!

**Comment by alisan16** [comment] 2020-03-31 19:08
This has been fixed with the new SSO (single sign on) that rolled out in March 2020.

**Closed by alisan16** 2020-03-31 19:08 UTC
Labels: Product: caseflow-eFolder-Express, bug-low-priority, in progress
