### ISSUE TITLE
Investigate missing downloads when rapidly clicking away

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#233] opened 2016-10-05 13:24 UTC
From the usability tests in (https://github.com/department-of-veterans-affairs/appeals-pm/issues/674)

> If they clicked the "start retrieving eFolder" button and immediately thereafter clicked the eX logo to return home before the progress bar started moving, sometimes the system would not register the retrieval (i.e., it would not appear in their history). @orischwartz or @shanear is this something you could look into? I tried reproducing it in UAT and I did not experience the problem. i could see this being an issue if folks are queuing up many retrievals and moving quickly.

We should attempt to reproduce this issue, or investigate its possible causes.

**Comment by joofsh** [comment] 2016-10-13 13:04
After investigating this for a while, I cannot reproduce the issue.  Clicking the "Start Retrieving eFolder"  button triggers the DownloadsContoller `start` method, which updates the download row to a status of [pending_documents](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/controllers/downloads_controller.rb#L22). This is all done synchronously before reloading the page. Even executing the two clicks programmatically, I cannot catch the race condition.  To test this I did the following:

- Change config/application.rb,  adding  `config.allow_concurrency=true`
- Boot the app with many threads/workers: `puma -t 8:32 -w 3 config.ru -p 3000
- Search for a new filename, ie "DEMO99" 
- In the javascript console, enter the following:
```
$('form').submit();  // trigger "Start Retrieving eFolder" button form submit
setTimeout(function() { window.location.href = '/' }, 8) ; // Wait 8 miliseconds, then navigate to homepage
```

Navigating to the homepage any faster than 8 miliseconds and the POST /start request has not been sent yet (it seems to consistently takes 7 ms to send). Clicking within 8ms is way beyond human capabilities.  Unless there is a scenario that this line of testing does not cover, then this bug is not possible. 

Note:
From a UX perspective, I noticed a couple things that we may want to consider changing (I apologize if this has already been discussed and I'm out of the loop):
-  The homepage is a search back with a history list. From a UX standpoint I would expect the "History" section to be a history of all searches I have performed. Looking at how [recent_download](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/controllers/downloads_controller.rb#L88) is calculated, it excludes searches where we did not trigger the downloading the files. This may have been intentional from a workflow perspective, but as a new user it was a little jarring to perform a search, navigate back to the homepage, and to not see that search show up in the list
- Searches are not listed in chronological order. It seems like we could sort by `created_at`, or add an `updated_at` column and sort on that
<img width="954" alt="screen shot 2016-10-13 at 9 01 53 am" src="https://cloud.githubusercontent.com/assets/2256237/19349972/e2776404-9123-11e6-9276-0b950a3228fe.png">

**Comment by shanear** [comment] 2016-10-13 14:01
> Looking at how recent_download is calculated, it excludes searches where we did not trigger the downloading of files.

I've always had a hunch that this was the reason for the complaints. But I remember abby specifically saying they saw the screen with the loading bar.

**Comment by lakohl** [comment] 2016-10-13 21:50
@joofsh Regarding the History - We are only showing Vet IDs that were 'retrieved'. As in, they were Searched and then the user hit the 'Start Retrieveing eFolder' button. The History should show the most recent Search at the top and we'd like to break it up by date as detailed in: https://github.com/department-of-veterans-affairs/appeals-pm/issues/781

In terms of the fast clicking issue... @abbyraskin feel free to chime in. If you can't replicate it, I would say that it might be an edge case. I would put an icebox label on it for now and see if it get reported again.

**Comment by shanear** [comment] 2016-10-14 17:33
iced.

**Comment by Chingujo** [comment] 2017-11-08 14:54
Closing this out since its been iced for year and could not be reproduced and haven't seen this replicated going through some tickets a few months back. Please feel free to re-open in case I am missing some context!

**Closed by Chingujo** 2017-11-08 14:54 UTC
Labels: eFolder Express, Investigation, whiskey
