### ISSUE TITLE
History of in progress files not showing

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#991] opened 2018-04-18 15:02 UTC
## Context
The files that in progress in downloading do not show up in the history page

## Priority
High - in production and used frequently to queue and keep track of multiple downloads

## Reproduction
- Download a veteran file 
- Shows the download in progress
- Go back to home page
- The history does not show up that displays the download in progress

## Screen shots
_ In progress_
<img width="241" alt="screen shot 2018-04-18 at 10 55 42 am" src="https://user-images.githubusercontent.com/23316107/38940317-d65a718e-42f7-11e8-8c01-353e8867af12.png">

_Navigate to home no history_
<img width="928" alt="screen shot 2018-04-18 at 11 01 48 am" src="https://user-images.githubusercontent.com/23316107/38940370-f52aecd8-42f7-11e8-9f7c-c80605ccfda2.png">

**Comment by lowellrex** [comment] 2018-04-18 21:49
I am unable to reproduce this locally or in UAT. Can we get more information about the browser (tried Safari and Chrome and they both worked) and the OS? Perhaps this is a case where production is different than UAT and the local environment, but I am hesitant to jump to that conclusion until we have more information and can reproduce it in production.

**Comment by alisan16** [comment] 2020-03-31 19:10
Closing as this hasn't been updated in 2 years

**Closed by alisan16** 2020-03-31 19:10 UTC
Labels: Product: caseflow-eFolder-Express, bug-high-priority, in progress
