### ISSUE TITLE
[UI] Errors tab - source and receipt date are off

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#686] opened 2017-11-07 19:03 UTC
Source and Receipt Date are outside of the tab.

![image](https://user-images.githubusercontent.com/3811786/32512280-825da036-c3c4-11e7-8f9d-c811aa5f9bf7.png)

Notes:
1. Use DEMO3 locally to cause errored documents

AC:
1. Source and Receipt Date should be present for each failed documents.
2. Ensure Source and Receipt Date are inside the tab.

**Comment by kierachell** [comment] 2017-11-08 13:55
duplicate of https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/643

**Comment by kierachell** [comment] 2017-11-12 13:19
**PASSED**
<img width="1037" alt="screen shot 2017-11-12 at 8 19 30 am" src="https://user-images.githubusercontent.com/18075411/32699357-3d517582-c782-11e7-84ce-6200bae138ac.png">

**Closed by kierachell** 2017-11-12 13:19 UTC
Labels: bug-medium-priority, eFolder Express, In-Validation, whiskey
