### ISSUE TITLE
Files Retrieved | Zip File |  Contains duplicate files

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-efolder#365] opened 2017-01-24 22:23 UTC
# Description
When the user downloads the files, it contains what the user believes to be archived files creating duplicates.  The entire file plus duplicates are downloaded.  The User notices discrepancy in the file totals.  User has to go through each document comparing downloaded items to what is shown to determine which is a duplicate or archived, so she can delete.

_Follow up Questions to the user_
Are any other users that you know/knew of that is/was having this same issue? – yes
Are the hidden and archive files being saved in the zip file? yes

**Type of Bug:**
- [ ] Performance
- [ ] Security
- [x] Functional

**Environment:**
- [x] Production
- [ ] UAT
- [ ] Demo
- [ ] Development

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [x]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
1. Enter Veteran ID and click the **_Search_** button on the `eX Home` page.
1. Click on the **_Start retrieving eFolder_** button on the `Manifest `page.
1. Click on the **_Download eFolder_** button on the `File Retrival` page.
1. Open the downloaded zip folder.  
The entire file plus duplicates are downloaded.  The User notices discrepancy in the file totals.  
User has to go through each document comparing downloaded items to what is shown to determine which is a duplicate or archived, so she can delete.
 
## Screenshots
 n/a
# Related Issues
**_Support Ticket_**
Files Retrieved:  Pulls Hidden/Archived Files: Duplicates [#14](https://github.com/department-of-veterans-affairs/appeals-support/issues/14)

**Comment by nikitarockz** [comment] 2017-02-03 17:28
# Support Update - User Responded on 1/21/17 8:25am 
User report that they are still having this issue.

**Comment by aroltsch** [comment] 2017-02-16 19:21
In order to re-produce it, we need a Veteran's ID

**Comment by aroltsch** [comment] 2017-02-21 20:59
Based on the discussion with @nikitarockz, it was decided to move the issue back since the user was not able to provide us with the Veteran ID.

**Comment by kierachell** [comment] 2017-02-27 14:28
See if the API we use pulls archived/restricted documents.

**Comment by kierachell** [comment] 2017-02-27 15:09
And here's with **Archive Bin**
<img width="1084" alt="screen shot 2017-02-27 at 10 08 15 am" src="https://cloud.githubusercontent.com/assets/18075411/23366492/d9336b78-fcd4-11e6-98fe-15a887dd9637.png">
<img width="913" alt="screen shot 2017-02-27 at 10 08 07 am" src="https://cloud.githubusercontent.com/assets/18075411/23366493/d93481c0-fcd4-11e6-94c8-0a631bfbef87.png">

**Comment by nikitarockz** [comment] 2017-02-27 19:04
Based on email from Nicholas, he said the user should receive all files with the exception of Fiduciary file types.  This include hidden duplicates and archived files.  Further discussions will need to be had to determine new features.  

New features won't be able to happen until after the new VBMS API has been released.

**Comment by amprokop** [comment] 2017-04-24 17:45
according to @nikitarockz 's info from @nicholasholtz , this is expected behavior and we shouldn't change anything. Closing this issue.

**Closed** 2017-04-24 17:46 UTC
Labels: bug-medium-priority, feature-definition, foxtrot, Triage
