### ISSUE TITLE
Attempted to update a stale object: Download

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow-efolder#547] opened 2017-07-24 18:04 UTC
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/321/ 
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/329/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/510/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/489/ 
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/491/

**Comment by mmlumba** [comment] 2017-10-11 18:21
Related timeout errors for issue 510 in Sentry:
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/509/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/508/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/506/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/505/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/504/

**Comment by nickheiner-usds** [comment] 2017-10-27 18:56
I can see that Sentry issue 329 is related, because it has the same error message as Sentry issue 510. But why do we think the others are related?

**Comment by nickheiner-usds** [comment] 2017-10-27 19:00
@amprokop is this related to #650?

**Comment by nickheiner-usds** [comment] 2017-10-27 19:05
Possibly related: #626.

**Comment by aroltsch** [comment] 2017-11-06 19:05
Duplicate of https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/650

**Closed by aroltsch** 2017-11-06 19:05 UTC
Labels: prod-alert, tango
