### ISSUE TITLE
Sentry Error - no implicit conversion of nil into String

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow-efolder#599] opened 2017-08-16 17:17 UTC
Possibly related to this commit: https://github.com/department-of-veterans-affairs/caseflow-efolder/commit/d9a003bf324047b1ec9859e78e591c067085fe2c

Sentry error: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/363/

![image](https://user-images.githubusercontent.com/3811786/32501682-a169e0f2-c3a6-11e7-8ef0-fc6bdd060d27.png)

**Comment by joofsh** [comment] 2017-08-21 19:05
occurred again 8/21

**Comment by mdbenjam** [comment] 2017-08-23 19:46
So digging into the sentry error it seems like there is something wrong with download 38342. Exactly one document doesn't have a filepath. I don't fully understand our retry logic, but it appears that our job is being retried and just keeps failing which throws the sentry error.

Note the retry_count in the image below. I've looked a lot of the instances of this event and it seems it's the same download over and over.
<img width="628" alt="screen shot 2017-08-23 at 3 45 02 pm" src="https://user-images.githubusercontent.com/3885236/29635140-167a0f5c-881a-11e7-9643-bfd2ba530dfa.png">

I think we should just delete this download object, and let the person re-download. I don't love running a delete in rails console, so I'd like to get thoughts from others. @shanear @amprokop

**Comment by aroltsch** [comment] 2017-11-08 15:39
duplicate of https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/532

**Closed by aroltsch** 2017-11-08 15:39 UTC
Labels: eFolder Express, prod-alert, whiskey
