### ISSUE TITLE
XML generated PDFs can't be merged with other PDFs

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-efolder#231] opened 2016-09-27 16:00 UTC
I witnessed @nicholasholtz attempting to download an eFolder. He was succesful in downloading the full contents of the eFolder but one of the files (I believe a VA Form 8 generated from Certification)  could not be combined into a single PDF with the other documents. Adobe threw and error citing the fact that the PDF was generated as XML. We should look into this, especially if these files are only generated by us in Certification. We should see if we can upload them as flat PDFs rather than XML PDFs. Follow up with Nicholas to get details.

**Comment by ariperez** [comment] 2016-09-29 13:27
@nicholasholtz , do you have some time to discuss this bug today?

**Comment by nicholasholtz** [comment] 2016-09-29 16:38
Sure – 3:30?

Nicholas B. Holtz
Counsel for Technology Integration
Board of Veterans’ Appeals
202.632.5105 | nicholas.holtz@va.gov<mailto:nicholas.holtz@va.gov>

This e-mail and any attachments are intended only for the use of the addressee(s) named herein and may contain privileged and/or confidential information. If you are not the intended recipient of this e-mail, you are hereby notified that any dissemination, distribution or copying of this e-mail, and any attachments thereto, is strictly prohibited. If you have received this e-mail in error, please notify me via return e-mail and via telephone at 202.632.5105 and permanently delete the original and any copy of any e-mail and any printout thereof.

**Comment by ariperez** [comment] 2016-09-29 17:28
that works for me. See you then.

**Comment by ariperez** [comment] 2016-09-29 20:40
Screenshot of the issue::
<img width="949" alt="screen shot 2016-09-29 at 4 36 50 pm" src="https://cloud.githubusercontent.com/assets/2553469/18971522/4c737f1c-8663-11e6-9e04-c79d34fda447.png">

**Comment by shanear** [comment] 2016-10-12 21:02
@ariperez I think i fixed the issue in certification. Can you test these two files and see which ones cause the issue?

[test-fdf-form8.pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/525588/test-fdf-form8.pdf)
[test-normal-pdf.pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/525589/test-normal-pdf.pdf)
[test-xfdf-form8.pdf](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/525587/test-xfdf-form8.pdf)

**Comment by nicholasholtz** [comment] 2016-10-12 21:08
Shane,
All can be combined in AdobePro without the XML error.

**Comment by shanear** [comment] 2016-10-12 21:23
Thanks @nicholasholtz. Unfortunately, that's kind of confusing because one of those should have failed.

Would you mind seeing if any in this zip fail?
[joesnuffy--20160930.zip](https://github.com/department-of-veterans-affairs/caseflow-efolder/files/525676/joesnuffy--20160930.zip)

**Comment by shanear** [comment] 2016-10-12 21:24
@nicholasholtz also post which version of Adobe Acrobrat Pro you're using

**Comment by nicholasholtz** [comment] 2016-10-13 12:04
All PDF files in the joesnuffy—20160930 zip file successfully combined.  Note that those in the _MACOSX folder, with format ._0000-etcetc were not recognized as valid Adobe file types by either Reader or Pro and could not be opened at all, much less combined – a mac vs. windows issue with PDFs?

Using Adobe Acrobat XI Pro Version 11.0.17.

**Comment by shanear** [comment] 2016-10-13 13:35
@ariperez could you send the # of the efolder that is causing the issue (and in what environment). Also which version of Adobe Acrobat pro you're using.

**Comment by shanear** [comment] 2016-10-18 15:04
Ok, it's confirmed that Caseflow Certificaiton is not causing this issue. It's being caused by manually filling out an PDF form and uploading that file.

Created a feature request to have eFolder Express fix this formatting issue when retrieving the files (#257).

Closing this one

**Closed** 2016-10-18 15:05 UTC
Labels: bug, launch blocker
