### ISSUE TITLE
[Bug] Corrupted zip files with large file sizes

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-efolder#854] opened 2018-02-02 19:26 UTC
### Summary
Large files - generally over 4GB are rendering a generic zip file cannot open in PC's. However, the zip file opens fine when downloaded on a MAC. 

### Priority
- Marking this as medium since the number has been growing (about 5) over the past month and half, which is prevalent for eFolder Express. This may also rise as we roll out to more users. However, not an app critical bug

### Steps
1. Log into eFolder Express production via Chrome browser
2. Complete download of file size over 4gb
3. Zip file successfully downloads
4. Click the downloaded zip file
5. Windows renders "Cannot open this zip file error"

### Solutions
- Support downloads the file from production and Lyncs it over
   - However, this does not work for all files 
- Zip file opens for MACS and using different zip programs such as WinRar - wondering if we are zipping files in an incompatible way for window when large files are involved?

### Related Issues (total 5) 
_There are also 2 more, which is a running issue. I solved one but there is an other where production download is not working on a windows machine_
[1326](https://github.com/department-of-veterans-affairs/appeals-support/issues/1326)
[1291](https://github.com/department-of-veterans-affairs/appeals-support/issues/1291)
[1190](https://github.com/department-of-veterans-affairs/appeals-support/issues/1190)
[1345](https://github.com/department-of-veterans-affairs/appeals-support/issues/1345)

**Comment by lowellrex** [comment] 2018-02-02 22:40
After chatting with @Chingujo we decided to delay implementing any technical solution until we have more data about this issue and can be more certain about why this is happening.

### Outstanding Questions

In order to guide us in choosing the correct technical solution to this problem, I think it would be valuable if we answered the following questions for every occurrence of this issue.

1. Does re-download the zip file from efolder express result in the re-downloaded zip file also having the same issue?
1. Do zip files of similar (or larger) sizes suffer from the same problems when attempting to open them on the same computer that experienced the original issue?
1. Can the zip file be transferred to another computer and opened on that other computer?

### Possible Causes

This list is far from exhaustive. The true root cause is likely not even on this list that may in some combination of factors listed below.

**Caveat**: I am including these here for the sake of transparency and to provide some background on why I think the questions above are worth investigating. This is only mildly-educated wild speculation and I do not endorse any of these possibilities as the actual root cause.

1. We could be creating zip files in such a way that makes some of them un-openable on Windows machines. Perhaps the library we use to create the zip files ([rubyzip](https://github.com/rubyzip/rubyzip)) changes the way it compresses files after the contents reach a certain size threshold. I think this explanation is unlikely because downloading the same zip file on a different computer, transferring that zip file to the computer that originally encountered the error, and opening it on that computer succeeds. If this were the explanation we would expect that to fail since the underlying file contents are no different.

1. The zips are corrupted while they are being created. Before we upload a zip file to S2, we write it to a tempfile. Since creating the zip file takes a long time (dozens of minutes, perhaps hours? I don't have exact data on how long on hand) it is possible that the operating system/hardware/something else burps and the zip itself is corrupt. I think this explanation is unlikely because downloading the same zip file on a different computer and opening it on that computer succeeds. If this were the explanation we would expect that to fail since the underlying file contents are no different and it would be un-openable on all computers.

1. The zip file is corrupted in transit to the end user. Since downloading these large zip files takes hours, it is possible that some network/OS/hardware hiccup causes the file to be un-openable when it finally finishes downloading. This is a variation on possible cause 2 but the systems doing the hiccuping are probably less reliable (less reliable internet connection, less powerful hardware, uncontrolled software on the computer) so this is a little more likely. This possibility is enticing but suffers from being largely non-falsifiable so I don't know how helpful it is.

### Possible Solutions

The only really viable solution I can think of given what we know at the moment is below.

1. If we determine that the size of the zip files is the sole cause of the issue we could analyze the file size of the constituent files and create multiple zip files, limiting each zip file to some agreeable size. This is not a trivial programming task, would require some changes to the efolder express UI, would likely result in a deteriorated user experience for folks who download large zip files without issue (documents in a single zip file is almost certainly preferable to those same documents being spread across 4 zip files), and would only be possible after we determined what that size limit should be.

**Comment by Chingujo** [comment] 2018-03-16 20:22
@lowellrex 




@lowellrex 

We had three more issues come in the last month. The solution so far has been to download off prod using a mac then

1.) Splitting the file into 2 gb chunks due to Lync limitations
2.) Lyncing to the user
3. ) Then the user merges the files once received

This takes about an hour to an hour and a half for support to do and don't think it's a sustainable way. I'll update the issue with the known data points and is something we should tackle after we roll out react and test for any react bugs.

**Comment by Chingujo** [comment] 2018-03-29 19:40
@lowellrex 
## New information from user and support 
Apparently when we get a Mac user to download the files and send it over the user into bits on Lync, it works. However, testing with Raven on a windows machine, it does not work. The problem is that Lync file transfer limits means that files have to be split in four plus times with thousands of documents. It also compromises the order of the files in the downloaded zip. 

The end user then has to combine the files. One user was just ignoring the file and was having it sit on shelves for a few months because it was continually not working (this appeal is stalled at this point.)

## Metrics
Few metrics here that might be helpful in de-prioritzing or prioritizing this issue: 

- Average time for support resolution per issue: 3-4 hours or + depending on file size including splitting and ordering
  - Came with talking with support on time spent debugging. I was way off here and assumed 2 based on a smaller file
  - The vast time spent is splitting the files and then working with the user to get all split zip files sent in a timely way
   - This excludes the download time since that is just waiting 
- Volume: 4-6 a month
- File size range: 5 to 10 gb 
- Document range: 4000 to 11,000 documents (currently getting more accurate info)
- Total support time given a frequency of 5: 15-20 hours

**Comment by Chingujo** [comment] 2018-03-30 15:36
## Next steps

- [ ] Phillip to provide file numbers of downloads that did not work and Mark or Lowell to look at the stats in S3 
- [ ] Better understand the splitting zipping and merging process? What is taking the longest amount of time?  (Phillip) 

## Open questions
- Are we okay just not supporting this and letting users know that they have to use the old methods for these edge cases?

- Are these happening for all file sizes? Initial guess is no.

- Can we reduce the support effort? (Optimize the process or can we tag team with PO to triage?

**Comment by Chingujo** [comment] 2018-03-30 17:29
@lowellrex 

Checked S3 and found that these happen around 1/500 and 1/1000 and may occur at or a similar file size. Thanks champ!

**Comment by pkarman** [comment] 2020-01-15 17:40
Should be fixed by #1141

**Closed by pkarman** 2020-01-15 17:40 UTC
Labels: bug-medium-priority, eFolder Express, in progress
