### ISSUE TITLE
Downloads for cases that are not found should not be cached for later use

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#195] opened 2016-08-18 14:59 UTC
See _When user enters a number they already entered, it goes to the existing download_ #120 for original implementation of this

* If connection to BGS fails, the case will appear as not found
* Attempting to search for the same case again later will direct user back to the original download that wasn't found, 
* Instead, we should attempt the search again

**Comment by orischwartz** [comment] 2016-08-22 17:23
@shanear I still encountered this bug with a download that had a status of `2` ( `pending_confirmation`). I received the *eFolder Express could not find any documents in the eFolder with ID* message. Once I manually updated the cached download's status column to 1, the search succeeded.

```
efolder_express=> select * from downloads where id=43;
 id | request_id | file_number | status |         created_at         |        updated_at        | user_station_id |  user_id  | lock_version | veteran_name |    manifest_fetched_at     | started_at | completed_at
----+------------+-------------+--------+----------------------------+--------------------------+-----------------+-----------+--------------+--------------+----------------------------+------------+--------------
 43 |            | 2******2    |      2 | 2016-08-18 14:22:20.952536 | 2016-08-18 14:22:22.7792 | 283             | ********* |            2 | **********   | 2016-08-18 14:22:22.771024 |            |
(1 row)
```
Search for above `file_number` fails to find documents. After executing `update downloads set status=1 where id=43;`, the search succeeds.

Any idea why the search wasn't retried with a status of 2?

**Comment by orischwartz** [comment] 2016-08-22 17:36
Update: going to re-open this. Encountered same issue on a case with status of `complete_with_errors: 6`

**Comment by shanear** [comment] 2016-08-22 18:25
@orischwartz the error here is that a download that wasn't found was ever a status of 2 to begin with. Pending confirmation means that the manifest was found and the download needs to be confirmed. Looking into why that download was erroniously marked a 2.`

`complete_with_errors` signifies that download completed. Just one or more documents failed. We decided to continue to cache these downloads, but offer a "retry" button, which wipes the download and restarts it.

**Comment by shanear** [comment] 2016-08-24 15:30
this is caused by #200, closing

**Closed** 2016-08-24 15:30 UTC
