### ISSUE TITLE
History Section:  Section not showing up for the first retrival request

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#298] opened 2016-11-28 21:12 UTC
While performing a search for a file, the entire History section including the requested veteran name and ID information is not showing up for the first veteran on the eFolder Express landing page.  The History section does show up when I perform a second file retrieval request.   

### Reproduction Steps
1. Enter Vet ID number in the search.
1. Click the Search button.
1. Click on the Start Retrieving eFolder button.
1. While file is being retrieved, click on the eFolder Express logo.  
1. The landing page is displayed.  There is no History section showing on the eFolder landing page nor does the first file being requested show.

Refer to images below in comments

**Comment by lakohl** [comment] 2016-11-28 21:15
Normally a file in the process of being retrieved should still show in the History.

I searched for Vera Marshall, then went back to home to search for a new Vet ID. The History section was still not visible on the eX homepage.
<img width="887" alt="screen shot 2016-11-28 at 12 05 44 pm" src="https://cloud.githubusercontent.com/assets/4975959/20678155/b65566aa-b563-11e6-8eda-36d1b3d36f9a.png">
<img width="872" alt="screen shot 2016-11-28 at 12 05 51 pm" src="https://cloud.githubusercontent.com/assets/4975959/20678160/b9abb6f6-b563-11e6-98b0-e563eb9c2c6b.png">

**Comment by lakohl** [comment] 2016-11-28 21:33
This is what the History at the bottom of the landing page should look like:
<img width="846" alt="screen shot 2016-11-28 at 4 32 17 pm" src="https://cloud.githubusercontent.com/assets/4975959/20686890/4f8e65f0-b588-11e6-88dc-b430390e55ab.png">

**Comment by lakohl** [comment] 2016-12-06 17:02
@nemodjuric this occurred in UAT

**Comment by nemodjuric** [comment] 2016-12-08 20:34
This was not reproducible either locally or in UAT. Both @lakohl and @cmgiven were not able to reproduce in UAT. 
If this happens again, we should take a note of time and look through environment logs.

**Comment by lakohl** [comment] 2016-12-08 20:39
I just checked the time stamp on the screenshots I took when I first noticed this issue. It occurred on Nov 28,2016 at 12:05 pm.

**Comment by shanear** [comment] 2016-12-09 22:47
This may have been fixed by the user caching issue (the download was created for a different user due to a bug). We haven't seen the problem reproduced. We'll keep an eye out, closing for now.

**Closed by shanear** 2016-12-09 22:47 UTC
Labels: bug, foxtrot, In Progress
