### ISSUE TITLE
Issues with email address and CSS ID

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#569] opened 2017-08-02 17:46 UTC
1. Email address have spaces in front of them. E.g, email: "  Tecola.Plowden@va.gov"
2. We will not worry about converting css_ids to upper case in our DB. We need to think about CSS IDs more. Previously, all CSS IDs were upper case then at some point in time some users CSS IDs were changed to include a combination of upper/lower case. Was it a one time change for the existing users? If yes, once we clean up the duplicates, we will not run into the same problem again.

AC:
1. Ensure emails don't have spaces. Create a migration to clean up existing emails
2. Write a migration to clean up duplicate user records, use the latest css_id for user
3. Test both migrations on the DB prod copy

**Comment by amprokop** [comment] 2017-08-09 14:18
@aroltsch — would you mind giving some context on this issue? I think you said that FeatureToggles didn't work properly because of these, are there other problems that were created?

**Comment by aroltsch** [comment] 2017-08-09 15:01
@amprokop It causes a few issues:
1. Emails have empty spaces - makes it more difficult to search for a user by email
2. We have duplicate User records for the same user due to CSS ID discrepancies: we might have up to 3 user records with the same css id, the only difference is upper/lower case letters. 
3. Problems with a feature toggle due to upper/lower case letter combinations in CSS IDs: https://github.com/department-of-veterans-affairs/caseflow-commons/issues/111

**Comment by lowellnava** [comment] 2017-11-16 21:04
@aroltsch two questions:

1. Do we want to remove all spaces from an email address, including spaces in the username/local part (i.e. "king zombo@zombo.com" would become "kingzombo@zombo.com"), or do we want to remove only leading and trailing whitespace from the email address ("       king zombo@zombo.com " would become "king zombo@zombo.com")?

2. When we store the CSS IDs in the database do we want to convert all characters to uppercase (or lowercase)? Or do we want to retain the casing of the CSS ID and ensure the CSS ID is unique regardless of case (perhaps by using [validates_uniqueness_of()](http://api.rubyonrails.org/classes/ActiveRecord/Validations/ClassMethods.html#method-i-validates_uniqueness_of) with :case_sensitive set to false)?

**Comment by lowellnava** [comment] 2017-11-16 22:25
@aroltsch Another question, should Users' CSS_IDs be unique by themselves, or should only the combination of CSS_ID and station_ID be unique?

**Comment by aroltsch** [comment] 2017-11-17 12:16
@lowellnava 
1. I am pretty sure VA email addresses don't have spaces in the middle so yes only leading and trailing whitespace.
2. I think we should convert them all to uppercase in the database. @shanear do you have an opinion on that?
3. CSS id should be unique by themselves

**Comment by shanear** [comment] 2017-11-17 15:09
> I think we should convert them all to uppercase in the database.

I agree, but this will also require a code change. We need to convert the css_id that we pull in from the cookies to uppercase too.

PS. this is an annoying problem 🐘 😄 

> CSS id should be unique by themselves

Are you sure this is true? It might be, but we've always considered CSS id + station id to be unique.

**Comment by aroltsch** [comment] 2017-11-17 16:01
Yes, @shanear, Lowell and I chatted and realized CSS id + station id should be unique, not just CSS id.

**Comment by lowellnava** [comment] 2017-11-17 17:47
@aroltsch @shanear Will we be updating existing records in the database so that their CSS_IDs are capitalized? I am in support of NOT changing existing database records, however, if we do not update existing database records then we will end up creating new records for each row that has a lowercase letter in their CSS_ID (though that really is just the upper bound, the real number is probably far lower). I will do some digging into the data to see what that upper bound actually is.

**Comment by lowellnava** [comment] 2017-11-17 18:27
Chatted with @aroltsch and will delay worrying about altering existing data (will only affect ~70 records in the table of ~900) until a later date.

**Comment by lowellnava** [comment] 2017-11-17 21:53
Script to update the tables that reference a duplicate user record due to the css_id casing issue once this code is live could look something like:

* Update user_id fields that reference duplicate user records (user records created after another with the same case-insensitive css_id and station_id combination) across all tables (downloads, searches, and user_manifests as far as I can tell):
```
with t as (
  select
    a.id original_id,
    b.id duplicate_id
  from users a
  join users b
    on upper(a.css_id) = upper(b.css_id)
    and a.station_id = b.station_id
    and a.created_at < b.created_at
)
update downloads     # searches|user_manifests
set user_id = t.original_id
from t
where user_id = t.duplicate_id;
```

* Delete the duplicate user records.
```
delete
from users
where id in (
  select
    b.id
  from users a
  join users b
    on upper(a.css_id) = upper(b.css_id)
    and a.station_id = b.station_id
    and a.created_at < b.created_at
);
```

* Capitalize all css_ids in the user table.
```
update users set css_id = upper(css_id);
```

**Comment by shanear** [comment] 2017-11-17 22:02
@lowellnava Looks good, but it's hard for me to trace out the joins so I'm not 100%. I think i'd be more comfortable with the script being in Ruby, so you can be a little bit more explicit and expressive with the logic.

You can also just slide it into a migration that way.

**Comment by lowellnava** [comment] 2017-11-17 22:27
@shanear I've described what the sql statement at the core of that script is doing below. The overall goal of this statement is to gather a list of all rows in the users table that have the same station_id and css_id (regardless of case) of a row that was created before it.
```
# Get the current row's id (duplicate_id) as well as the id
# of the row this row duplicates (original_id).
  select
    a.id original_id,
    b.id duplicate_id
# Join the users table against itself...
  from users a
  join users b
# where the css_id of the left and right tables match
# regardless of case...
    on upper(a.css_id) = upper(b.css_id)
# and station_id are the same...
    and a.station_id = b.station_id
# and the left table's row was created before the right
# table's row so we only get one row for each duplicate.
    and a.created_at < b.created_at
```

As for writing this in Ruby, I'm not sure I have a good sense of how or why we would do that. I'm still mostly a stranger to the Ruby/Rails world so I'm up for understanding the most idiomatic way of accomplishing this task!

Would we just write a script to create the appropriate ActiveRecord models from the database and then filter/map over those models? Is there a rails migration magic way of writing such a script? And do we get some added benefit (ability to rollback transaction if it fails? reverse the transaction/rewind the db to the previous state?) from doing it inside Ruby instead of the database itself?

**Comment by kierachell** [comment] 2017-11-17 23:26
💯 on the SQL!

You can make it reversible too: https://stackoverflow.com/a/29765612

**Comment by shanear** [comment] 2017-11-20 16:33
👍 on the SQL, especially if we test it.

Running it with ruby can take advantage of Rails built in migration system. Which has the side effect of documenting exactly what was run, and checking the migration into source code, etc.
(you can also do this by running the raw SQL from the ruby code, but I'm not sure how it treats multistatement SQL commands with variables and stuff)

**Comment by aroltsch** [comment] 2017-11-22 17:10
FYI, changing AC.

**Comment by lowellrex** [comment] 2017-11-27 23:59
Scope on this ticket was reduced to include only the two PRs. Remaining work to accomplish this effort (proper sanitization of incoming data from CSS) will be done as a part of #740.

**Comment by lowellrex** [comment] 2017-11-28 13:58
@kierachell I've tested these sql scripts locally and they work, but you mentioned spinning up a snapshot of prod to test this before we push it live. If you have time today could you walk me through what it takes to make that happen?

**Comment by astewarttistatech** [comment] 2017-11-28 14:30
@lowellrex  this sounds like something else needs to be done with this ticket. Is it ready for validation?

**Comment by lowellrex** [comment] 2017-11-28 14:37
@astewarttistatech Yes and no. @kierachell is whipping up a database we can test against to make sure the migration transforms the data as expected (and we don’t wipe out any data we didn’t mean to). I am confident the code works, so that is probably more of a just a validation step. However, I would like to be a little involved just so I can increase my level of confidence with the rails magic that is running sql statements by way of rails migrations.

**Comment by kierachell** [comment] 2017-11-28 15:34
**PASSED**

- Validated that new users were deleted and their data was mapped onto old user IDs
- Validated that all CSS_IDs were set to old CSS_IDs for consistency
- Validated that searches were remapped onto old user IDs


### Caveats
- deploy will require killing user sessions to update CSS/IDs/Emails
- probably should be done during off-hours
- might have to kill some sidekiq jobs that use old objects that reference old user IDs

**Comment by lowellrex** [comment] 2017-11-28 19:00
@mdbenjam had a very clever solution for a way to avoid the impending complicated deployment (with user session killing, sidekiq job purging, and way after hours deployment fun), so I am re-opening this issue.

As the migrations are currently written, when there are multiple user records in the table that relate to the same case-insensitive css_id and station_id we delete all but the oldest one and use the css_id from the newest matching record. Since we expect users to always be logging in with the most recently created matching row in the user table this could result in an active session (or queued job) with a user ID that we have deleted as a result of this migration. The somewhat convoluted deployment process sought to address that problem.

Instead--and here we truly get to the heart of @mdbenjam's genius--we could just delete all but the newest matching record (and update the database accordingly). Since all active sessions and queued jobs should relate to the newest matching record in the user table, we can deploy this migration without fear! We will simply need to amend this migration to keep the newest record, and update that record with the  oldest matching record's created_at timestamp.

cc @aroltsch @shanear @kierachell

**Comment by lowellrex** [comment] 2017-11-28 19:13
@kierachell is verifying that the newest of matching user records is always the one that users are logging in with by checking to see that searches/downloads for matching user_ids that relate to matching users only go in one direction. Once we start seeing a newer user_id pop up for a user that matches an previously existing user we should stop seeing the user_id for the older user.

For example, if user ID 15 is really a duplicate of user ID 3, every search or download we see for user ID 15 should happen after the most recent search/download for 3.

**Comment by lowellrex** [comment] 2017-11-28 19:31
id   |         created_at         | user_id
-------|----------------------------|---------
 67208 | 2017-11-17 16:40:59.284562 |      70
 43817 | 2017-07-24 19:24:06.199275 |     250
 43815 | 2017-07-24 19:22:29.955661 |     250
 43814 | 2017-07-24 19:21:46.34016  |     250
 43809 | 2017-07-24 19:16:19.022287 |     250
 43808 | 2017-07-24 19:15:03.027631 |     250
 28931 | 2017-05-10 20:49:18.202709 |      70
 28928 | 2017-05-10 20:42:01.218198 |      70
 25898 | 2017-04-25 13:26:46.84629  |      70

@kierachell found a counter-example that disproves the above assumption. I think the css_id migration will have to wait until #740 is ready to go to be released.

**Comment by lowellrex** [comment] 2017-11-28 21:40
Back to validation with this ticket. Users' css_id migration has been delayed, but the trimming of existing email addresses (can be validated by running `select count(*) from users where email <> trim(email);` or similar and seeing a result of 0) and new emails as they are saved to the database.

**Comment by kierachell** [comment] 2017-11-29 13:01
**PASSED**
aaaah


I passed it already....
or...something

**Closed by kierachell** 2017-11-29 13:01 UTC
Labels: bug-low-priority, eFolder Express, In-Validation, whiskey
