### ISSUE TITLE
[UI] JS console errors

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow-efolder#793] opened 2017-12-20 11:27 UTC
Notes:
![image](https://user-images.githubusercontent.com/3811786/34205053-efdcbd1c-e54e-11e7-9de4-682d3ac05eea.png)

**Comment by lowellrex** [comment] 2018-02-27 21:36
Closing this out as a duplicate of #866.

**Closed by lowellrex** 2018-02-27 21:36 UTC
Labels: eFolder Express, whiskey
