### ISSUE TITLE
Download eFolder:  Error message received when downloading

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-efolder#299] opened 2016-11-28 21:43 UTC
OGC Contractors reported that they had trouble downloading the zip file for two cases. More than one contractor had the same issue and I was able to replicate it on my machine as well. Will send screenshots over lync.  Suspect it might have something to do with the size of the efolder (large) and causing a time out issue.

### Reproduce Steps
1. Enter Veteran ID.
1. Click on the Search button
1. Wait for the retrieval process to be completed.
1. Click on the View Results link.
1. Click on the Download eFolder button.
1. The following message is displayed:
eFolder Message:  The [Veteran Name].zip download was interrupted. 
Or
Browser Message:  "Source file could not be read."
Or
Browser Message:  "No documents found"

Refer to images below.  You will need to contact @lakohl to get specific IDs.

**Comment by lakohl** [comment] 2016-11-28 22:01
![lk_reproduces error](https://cloud.githubusercontent.com/assets/4975959/20687902/56d4b734-b58c-11e6-8a34-d1aa096391ea.png)

**Comment by lakohl** [comment] 2016-11-28 22:08
I have real vet ID #s I can share over Lync for debugging

**Comment by nemodjuric** [comment] 2016-12-06 15:10
@shanear What are the reproduction steps for local instance?

**Comment by shanear** [comment] 2016-12-06 19:18
This is only reproducible on prod with certain eFolders, youll need to pair with Alan or me. Save this one for next week.

**Comment by askldjd** [comment] 2016-12-06 20:48
I looked into this with @nemodjuric, @lakohl, and @joofsh 

@lakohl demonstrated this with a prod case, and the we found out that the zipped file is > 1.4GB. During the download, the browser displays "Unknown File Size" with a spinner, which indicates that the `content-length` header is not set.

At a glance, we see two possibilities

1. Because of the scary looking "Unknown File Size" message, this large download gives the user the feeling of an endless download. User ends the download early, and gets a corrupted zip file.

1. Efolder are prematurely killing the download connection early and lead to a corrupted zip file.

At minimum, I would suggest to add `content-length` [header](http://stackoverflow.com/questions/29485042/how-to-set-content-length-by-send-file) to [send_file](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/controllers/downloads_controller.rb#L62) to make sure we display download progress correctly. Afterward, we should re-test to see if it addresses the issue.

**Comment by shanear** [comment] 2017-01-09 14:41
Added "Content-Type" header. See #350 for validation info.

**Comment by kierachell** [comment] 2017-01-09 15:06
Can't test large sizes in `demo` but the header does show right now:
<img width="896" alt="screen shot 2017-01-09 at 10 04 39" src="https://cloud.githubusercontent.com/assets/18075411/21770888/3f467be2-d653-11e6-80f2-849c39642526.png">

**Comment by askldjd** [comment] 2017-01-10 15:45
Downloaded a large efolder (310MB), and the full efolder size is showing up correctly in the browser during download.

Closing.

**Closed by askldjd** 2017-01-10 15:45 UTC
Labels: bug, foxtrot, In Validation
