### ISSUE TITLE
StaleObjectError thrown while updating a document

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow-efolder#521] opened 2017-07-05 15:52 UTC
This is a message seen in Sentry

```
ActiveRecord::StaleObjectError: Attempted to update a stale object: Document
```

Link to the sentry logs: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/271/

**Comment by kierachell** [comment] 2017-07-20 15:17
### Happening consistently in UAT using 879325490:
```
[ActiveJob] [DownloadManifestJob] [2792145e-1710-43c3-86a2-7870085739c8] [2017-07-20 11:14:08 -0400]   SQL (1.7ms)  INSERT INTO "documents" ("document_id", "download_id", "type_id", "type_description", "source", "mime_type", "received_at", "created_at", "updated_at", "lock_version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["document_id", "{07AAFFFA-615D-4C47-8B01-E517953282D8}"], ["download_id", 548], ["type_id", "27"], ["type_description", "BVA Decision"], ["source", "VACOLS"], ["mime_type", "application/pdf"], ["received_at", "2017-04-23 00:00:00.000000"], ["created_at", "2017-07-20 15:14:08.773865"], ["updated_at", "2017-07-20 15:14:08.773865"], ["lock_version", 0]]                                                                                                                                 dsva-appeals-efolder_worker-uat/opt/efolder-express/src/log/efolder-express-worker.out i-0cc65de646e5fd7a0-172.30.70.29 [ActiveJob] [DownloadManifestJob] [2792145e-1710-43c3-86a2-7870085739c8] [2017-07-20 11:14:08 -0400]   SQL (1.8ms)  UPDATE "downloads" SET "manifest_fetched_at" = '2017-07-20 15:14:08.776453', "updated_at" = '2017-07-20 15:14:08.776902', "lock_version" = 1 WHERE "downloads"."id" = $1 AND "downloads"."lock_version" = $2  [["id", 548], ["lock_version", 0]]dsva-appeals-efolder_worker-uat/opt/efolder-express/src/log/efolder-express-worker.out i-0cc65de646e5fd7a0-172.30.70.29 [ActiveJob] [DownloadManifestJob] [2792145e-1710-43c3-86a2-7870085739c8] [2017-07-20 11:14:08 -0400]    (1.7ms)  ROLLBACK                                                                                                                                                                                                                                           dsva-appeals-efolder_worker-uat/opt/efolder-express/src/log/efolder-express-worker.out i-0cc65de646e5fd7a0-172.30.70.29 [ActiveJob] [DownloadManifestJob] [2792145e-1710-43c3-86a2-7870085739c8] [2017-07-20 11:14:08 -0400] Performed DownloadManifestJob from Sidekiq(default) in 6000.29ms                                                                                                                                                                                               dsva-appeals-efolder_worker-uat/opt/efolder-express/src/log/efolder-express-worker.out i-0cc65de646e5fd7a0-172.30.70.29 [2017-07-20 11:14:08 -0400] Failure! Retry 0 in 33 seconds                                                            dsva-appeals-efolder_worker-uat/opt/efolder-express/src/log/efolder-express-worker.out i-0cc65de646e5fd7a0-172.30.70.29 [2017-07-20 11:14:08 -0400] fail: 6.007 sec                                                                           dsva-appeals-efolder_worker-uat/opt/efolder-express/src/log/efolder-express-worker.out i-0cc65de646e5fd7a0-172.30.70.29 [2017-07-20 11:14:08 -0400] {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"DownloadManifestJob","queue":"default","args":[{"job_class":"DownloadManifestJob","job_id":"2792145e-1710-43c3-86a2-7870085739c8","queue_name":"default","arguments":[{"_aj_globalid":"gid://caseflow-efolder/Download/548"}],"locale":"en"}],"retry":true,"jid":"13d6c10886ddb1f9aca99fea","created_at":1500563642.8666847,"enqueued_at":1500563642.8668084,"error_message":"Attempted to update a stale object: Download","error_class":"ActiveRecord::StaleObjectError","failed_at":1500563648.783541,"retry_count":0},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"DownloadManifestJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"DownloadManifestJob\",\"job_id\":\"2792145e-1710-43c3-86a2-7870085739c8\",\"queue_name\":\"default\",\"arguments\":[{\"_aj_globalid\":\"gid://caseflow-efolder/Download/548\"}],\"locale\":\"en\"}],\"retry\":true,\"jid\":\"13d6c10886ddb1f9aca99fea\",\"created_at\":1500563642.8666847,\"enqueued_at\":1500563642.8668084}"}                                                                                                                                                                                 dsva-appeals-efolder_worker-uat/opt/efolder-express/src/log/efolder-express-worker.out i-0cc65de646e5fd7a0-172.30.70.29 [2017-07-20 11:14:08 -0400] ActiveRecord::StaleObjectError: Attempted to update a stale object: Download              dsva-appeals-efolder_worker-uat/opt/efolder-express/src/log/efolder-express-worker.out i-0cc65de646e5fd7a0-172.30.70.29 [2017-07-20 11:14:08 -0400] /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/locking/optimistic.rb:102:in `_update_record'
```

**Comment by aroltsch** [comment] 2017-11-06 19:08
duplicate of https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/650

**Closed by aroltsch** 2017-11-06 19:08 UTC
Labels: bug-medium-priority, foxtrot, prod-alert
