### ISSUE TITLE
SPIKE: Figure out if we need to filter out Non-Restricted Fiduciary Type documents

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#450] opened 2017-04-05 19:54 UTC
DocTypes: 

```
#<OpenStruct upload_document_response={:veteran_reference=>{:id=>{:@file_number=>"561349912"}, :@xmlns=>""}, :type_category=>{:@xmlns=>"", :@category_id=>"18", :@category_description_text=>"Fiduciary
", :@type_id=>"549", :@type_description_text=>"Change of Address Beneficiary", :@type_label_text=>"L549"}, :va_receive_date=>Wed, 05 Apr 2017, :vbms_upload_date=>Wed, 05 Apr 2017, :@xmlns=>"http://servi
ce.efolder.vbms.vba.va.gov/eFolderUploadService", :"@xmlns:com"=>"http://vbms.vba.va.gov/cdm/common/v4", :"@xmlns:efc"=>"http://service.efolder.vbms.vba.va.gov/common", :"@xmlns:efu"=>"http://service.ef
older.vbms.vba.va.gov/eFolderUploadService", :"@xmlns:part"=>"http://vbms.vba.va.gov/cdm/participant/v4", :"@xmlns:doc"=>"http://vbms.vba.va.gov/cdm/document/v5", :@new_document_version_ref_id=>"{730F1E
35-E4D0-44A7-8229-989EF7F5B8B9}", :@document_series_ref_id=>"{184B5BF1-9128-479D-9D88-BDA58FE39983}", :@mime_type=>"application/pdf"}>
```

```
#<OpenStruct upload_document_response={:veteran_reference=>{:id=>{:@file_number=>"561349912"}, :@xmlns=>""}, :type_category=>{:@xmlns=>"", :@category_id=>"18", :@category_description_text=>"Fiduciary
", :@type_id=>"211", :@type_description_text=>"VA 21-555 Certificate of Legal Capacity", :@type_label_text=>"L182"}, :va_receive_date=>Wed, 05 Apr 2017, :vbms_upload_date=>Wed, 05 Apr 2017, :@xmlns=>"ht
tp://service.efolder.vbms.vba.va.gov/eFolderUploadService", :"@xmlns:com"=>"http://vbms.vba.va.gov/cdm/common/v4", :"@xmlns:efc"=>"http://service.efolder.vbms.vba.va.gov/common", :"@xmlns:efu"=>"http://
service.efolder.vbms.vba.va.gov/eFolderUploadService", :"@xmlns:part"=>"http://vbms.vba.va.gov/cdm/participant/v4", :"@xmlns:doc"=>"http://vbms.vba.va.gov/cdm/document/v5", :@new_document_version_ref_id
=>"{5E4E2850-B9D3-4AC7-894C-0FCBEC8CFE50}", :@document_series_ref_id=>"{8CE64ACB-D756-47E6-8B82-4A781331D580}", :@mime_type=>"application/pdf"}>
```

```
#<OpenStruct upload_document_response={:veteran_reference=>{:id=>{:@file_number=>"561349912"}, :@xmlns=>""}, :type_category=>{:@xmlns=>"", :@category_id=>"18", :@category_description_text=>"Fiduciary", :@type_id=>"136", :@type_description_text=>"VA 21-592 Request for Appointment of Fiduciary Custodian or Guardian", :@type_label_text=>"L127"}, :va_receive_date=>Wed, 05 Apr 2017, :vbms_upload_date=>Wed, 05 Apr 2017, :@xmlns=>"http://service.efolder.vbms.vba.va.gov/eFolderUploadService", :"@xmlns:com"=>"http://vbms.vba.va.gov/cdm/common/v4", :"@xmlns:efc"=>"http://service.efolder.vbms.vba.va.gov/common", :"@xmlns:efu"=>"http://service.efolder.vbms.vba.va.gov/eFolderUploadService", :"@xmlns:part"=>"http://vbms.vba.va.gov/cdm/participant/v4", :"@xmlns:doc"=>"http://vbms.vba.va.gov/cdm/document/v5", :@new_document_version_ref_id=>"{0B4541E3-DDDF-4D8D-977D-7CE30CEA2574}", :@document_series_ref_id=>"{6724BC3F-64BE-48DC-9ACB-260FDFACB81C}", :@mime_type=>"application/pdf"}>
```

Are not Visible in VBMS UI, but are visible in eFolder:

<img width="729" alt="screen shot 2017-04-05 at 3 42 17 pm" src="https://cloud.githubusercontent.com/assets/18075411/24723689/7b442ee4-1a16-11e7-86c9-325ea313663d.png">
<img width="1035" alt="screen shot 2017-04-05 at 3 53 44 pm" src="https://cloud.githubusercontent.com/assets/18075411/24724148/1644fe9a-1a18-11e7-945f-2d5f16c75c1b.png">

**Comment by kierachell** [comment] 2017-04-07 00:57
Using our new FIDUC account from https://github.com/department-of-veterans-affairs/appeals-qa/blob/master/TestData/LOGINS.md

Still seeing only 4 documents for 561349912

**Comment by aroltsch** [comment] 2017-04-10 12:47
This is blocked because it is unclear what's the approach. 
@nicholasholtz @shanear

**Comment by kierachell** [comment] 2017-04-10 14:51
I have received a new user from VBMS team who is able to see the fiduciary documents for 561349912

**Comment by lakohl** [comment] 2017-04-11 13:58
In these types of instances eX typically mirrors what happens in VBMS. So if a user's permissions enable him/her to see on 4 docs in VBMS the same should be true in eX. @nicholasholtz can you think of any reasons why eX should do things differently? I'm less familiar with the difference between fiduciary permissions and restricted files and the reasoning behind those permissions.

**Comment by nicholasholtz** [comment] 2017-04-11 14:14
@lakohl I don't think it actually works that way. eX pulls more broadly, and includes documents I cannot see in VBMS.

**Comment by aroltsch** [comment] 2017-04-11 14:55
@lakohl eX doesn't check the user's role. We could implement the role checking for eX if this is something desired in the future. 
@shanear @amprokop

**Comment by shanear** [comment] 2017-04-11 16:42
@aroltsch not checking the role was a concious decision. We only use functions for permisisons checking inside of caseflow. We also don't have a good way to know what roles should have access to fiduciary documents and which ones shouldn't.

We could always add a "eFolder Express Fiduciary" function to caseflow and force ISOs to opt in.

**Comment by nicholasholtz** [comment] 2017-04-11 20:06
Email sent 4/10 after learning that David Klusman is out through July:

From: Holtz, Nicholas B. 
Sent: Monday, April 10, 2017 11:05 AM
To: Tomaselli, Lisa, VBAVACO
Cc: Klusman, David R., VBAVACO; Peak, Margaret L. (BVA)
Subject: Visibility of non-restricted Fiduciary File Types

Ms. Tomaselli, 
I am following up from an earlier conversation I had with Mr. Klusman, and have put a couple of questions below. As I discussed with Mr. Klusman, I am working closely with the Digital Service at VA, which is developing the Caseflow product for managing and processing all appeals in the department. The products we are creating rely on access to Veterans’ entire electronic records, so we need a clear understanding of whether there are certain document types that should not be visible to certain users.

We are well aware of the restriction on IVM document types. The more difficult question come in concerning those document types which are “fiduciary.” These documents are apparently restricted by some VA policy/policies (which I have not yet had the opportunity to review), but may also need to be seen by certain users (i.e., Board attorneys, OGC attorneys).

Question 1: Can you provide me any policies applicable to documents identified as “restricted”?

Additionally, while I have a full list of the “restricted” document types that are only visible for Fiduciary users, we have received a second list of document types from VBMS that are not identified as restricted on the master list, but are not visible to anyone but Fiduciary users:

136 VA 21-592 Request for Appointment of Fiduciary Custodian or Guardian
211 VA 21-555 Certificate of Legal Capacity
423 VA 21-555a Designation of Payee
444 Misuse - Referral to Office of Inspector General
548 Change of Address Fiduciary
549 Change of Address Beneficiary
586 VA 21-6898 Application for Amounts on Deposit for Deceased Veteran
717 Fiduciary - Facility License

Question 2: Can you explain why these documents are only visible to Fiduciary users, even though they are not marked as “restricted”? And should these be handled the same way all “restricted” documents are handled?

Thank you! I would be happy to help clarify my questions if they are not clear. At the moment we have engineers waiting to move forward on changes, but want to make sure that any changes are in line with VA policy.

Nicholas

Nicholas B. Holtz
Counsel for Technology Integration
Board of Veterans' Appeals
425 I Street, NW, Room 5E.115
Washington, DC 20001
202.632.5105 | nicholas.holtz@va.gov

**Comment by nicholasholtz** [comment] 2017-04-11 20:06
Follow-up email sent 4/11:

From: Holtz, Nicholas B. 
Sent: Tuesday, April 11, 2017 3:59 PM
To: Tomaselli, Lisa, VBAVACO
Cc: Klusman, David R., VBAVACO; Peak, Margaret L. (BVA); Gant-Curtis, Angela; Perez, Ariel E.
Subject: RE: Visibility of non-restricted Fiduciary File Types

Good afternoon, Ms. Tomaselli! 

I hope you are doing well. I just wanted to follow-up quickly to see if this is information you might have, or if there is someone else I should reach out to. We currently have Caseflow engineers who are blocked on the development of the necessary connections with Virtual VA, as they do not know yet how this should be coded.

If there is a better person to ask this question, please let me know, and I will reach out to him or her. Thank you!

Nicholas

Nicholas B. Holtz
Counsel for Technology Integration
Board of Veterans’ Appeals
202.632.5105 | nicholas.holtz@va.gov

**Comment by shanear** [comment] 2017-04-14 21:13
bump @nicholasholtz

**Comment by nicholasholtz** [comment] 2017-04-17 13:25
Submitted another follow-up today:

From: Holtz, Nicholas B. 
Sent: Monday, April 17, 2017 9:25 AM
To: Phillips, Chad B., VBAVACO
Cc: Klusman, David R., VBAVACO; Peak, Margaret L. (BVA); Gant-Curtis, Angela; Perez, Ariel E.; Tomaselli, Lisa, VBAVACO
Subject: RE: Visibility of non-restricted Fiduciary File Types in VBMS/VVA/Caseflow
Importance: High

Good morning Mr. Phillips, 
My name is Nicholas Holtz, and I am Counsel for Technology Integration at the Board of Veterans’ Appeals. As discussed below in my email to Ms. Tomaselli, I work closely with the Digital Service at VA team in the development of Caseflow, a tool to replace VACOLS for the management and processing of all appeals at VA. 

As you can see below, the Digital Service team, in working to integrate Caseflow with Virtual VA, needs information concerning restrictions on certain types of documents. I am reaching out to you, after locating your name in the VACO Fiduciary Staff Directory, because I have not been able to obtain a response with my inquiries to other individuals. 

Would you be able to put me in touch with an appropriate POC to address the two questions highlighted below at your earliest convenience? The Digital Service’s work is currently being held up based on a lack of necessary information concerning these documents.

Thank you!

Nicholas

Nicholas B. Holtz
Counsel for Technology Integration
Board of Veterans’ Appeals
202.632.5105 | nicholas.holtz@va.gov

**Comment by aroltsch** [comment] 2017-04-17 15:29
Thanks @nicholasholtz !

**Comment by nicholasholtz** [comment] 2017-04-21 11:44
More back and forth/government feet dragging:

From: Tomaselli, Lisa, VBAVACO 
Sent: Wednesday, April 19, 2017 12:18 PM
To: Holtz, Nicholas B.
Subject: RE: Visibility of non-restricted Fiduciary File Types in VBMS/VVA/Caseflow

Good afternoon Mr. Holtz,

I wanted to follow up and verify that you have received answers to your questions or have been pointed in the right direction. I also wanted to offer my sincere apologies that you did not hear back from me sooner. I was unexpectedly out of the office through last week and have just returned. 

Please let me know if you are still in need of assistance.  

Respectfully, 

Lisa Tomaselli
Chief, Pension Team 1
Pension and Fiduciary Service (21PF)
Veterans Benefits Administration
Office: (202) 461-9386

**Comment by nicholasholtz** [comment] 2017-04-21 11:45
From: Holtz, Nicholas B. 
Sent: Wednesday, April 19, 2017 12:44 PM
To: Tomaselli, Lisa, VBAVACO
Subject: RE: Visibility of non-restricted Fiduciary File Types in VBMS/VVA/Caseflow

Ms. Tomaselli, 
Not a problem! Thank you for getting back to me. Actually I have not received anything yet. Would you be able to address the questions, or point me in the direction of someone who could? 

Thanks!

Nicholas

Nicholas B. Holtz
Counsel for Technology Integration
Board of Veterans’ Appeals
202.632.5105 | nicholas.holtz@va.gov

**Comment by nicholasholtz** [comment] 2017-04-21 11:45
From: Holtz, Nicholas B. 
Sent: Friday, April 21, 2017 7:44 AM
To: Tomaselli, Lisa, VBAVACO
Subject: RE: Visibility of non-restricted Fiduciary File Types in VBMS/VVA/Caseflow

Ms. Tomaselli, 
Good morning. Following up again on this. Have you had a chance to track down these answers, or identify an appropriate POC?

Thank you.

Nicholas

Nicholas B. Holtz
Counsel for Technology Integration
Board of Veterans’ Appeals
202.632.5105 | nicholas.holtz@va.gov

**Comment by nicholasholtz** [comment] 2017-04-21 16:44
More updates, with actual progress this time. @aroltsch see below.

From: Tomaselli, Lisa, VBAVACO 
Sent: Friday, April 21, 2017 12:38 PM
To: Holtz, Nicholas B.
Subject: RE: Visibility of non-restricted Fiduciary File Types in VBMS/VVA/Caseflow

Good afternoon Mr. Holtz,

Yes! **As it pertains to the list of document types you noted, all of those documents are supposed to be restricted except for 21-592 and 21-555.** Those documents [21-592 and 21-555] should be viewable in both Virtual VA and VBMS. 

The remaining documents must be restricted because it contains third party information related to the Fiduciary, which cannot be accessible to the beneficiary or to anyone without a “need to know.”  Therefore, in order to protect the Fiduciary, the information is restricted to the Fiduciary hubs. 

Kathel Baker is the POC from Fiduciary who can answer any additional questions or concerns regarding Fiduciary-related forms or restrictions. 

I truly hope this information is helpful, and again, I apologize for the delay in providing a response. Please let me know if I can be of any further assistance. 

Respectfully, 

Lisa Tomaselli
Chief, Pension Team 1
Pension and Fiduciary Service (21PF)
Veterans Benefits Administration
Office: (202) 461-9386

**Comment by nicholasholtz** [comment] 2017-04-21 16:45
From: Holtz, Nicholas B. 
Sent: Friday, April 21, 2017 12:43 PM
To: Tomaselli, Lisa, VBAVACO; Baker, Kathel L., VBAVACO
Subject: RE: Visibility of non-restricted Fiduciary File Types in VBMS/VVA/Caseflow

Thank you, Ms. Tomaselli! 

Ms. Baker, 
Good afternoon. I am an attorney at the Board of Veterans’ Appeals, working closely with the Digital Service at VA, as they develop the Caseflow suite of products for managing and processing all appeals in the Department. As discussed below, the products we are creating rely on access to Veterans’ entire electronic records. I am trying to obtain a clear understanding of whether there are certain document types that should not be visible to certain users, and I was hoping you might be able to provide me with any Fiduciary-specific policies or guidance that might illuminate this issue for me.

I appreciate you taking the time to address this, as it will make a big impact for our team. We have a group of engineers that is ready to move forward on further integrations once we have full visibility on how these documents need to be handled.

Thank you!

Nicholas

**Comment by nicholasholtz** [comment] 2017-04-26 15:33
@aroltsch Had conversation with Fiduciary rep yesterday. Waiting on follow-up today. Key takeaway on those 8 doc types (which she is getting confirmation on): 

These doc types do not need to be kept out when we are pushing docs through:
136 VA 21-592 Request for Appointment of Fiduciary Custodian or Guardian
211 VA 21-555 Certificate of Legal Capacity
423 VA 21-555a Designation of Payee
586 VA 21-6898 Application for Amounts on Deposit for Deceased Veteran
717 Fiduciary - Facility License

She thinks these 3 still need to be hidden:
444 Misuse - Referral to Office of Inspector General
548 Change of Address Fiduciary
549 Change of Address Beneficiary

I am simultaneously trying to push them to actually create either a consistency across the restricted/non-restricted labels, or a clear policy on this - they don't seem to have a policy in existence, it is all based on just how things are done.

**Comment by nicholasholtz** [comment] 2017-04-26 21:28
Confirmation:

From: Baker, Kathel L., VBAVACO 
Sent: Wednesday, April 26, 2017 3:21 PM
To: Holtz, Nicholas B.
Cc: GOLDSTEIN, SHAWN, VACO
Subject: RE: Visibility of non-restricted Fiduciary File Types in VBMS/VVA/Caseflow

Good afternoon, 

As we discussed, **the following document types are associated with the fiduciary user role, but not restricted**.  P&F Service does not require that the below documents are restricted.  Shawn and I spoke earlier today and he advised that unrestricted documents should transfer to CaseFlow regardless of the user role associated with the documents.  I have included Shawn on the email to assist with questions related to the visibility of non-restricted documents that are associated with a specific user role. 

**•	VA 21-592 Request for Appointment of Fiduciary Custodian or Guardian
•	VA 21-555 Certificate of Legal Capacity
•	VA 21-555a Designation of Payee
•	VA 21-6898 Application for Amounts on Deposit for Deceased Veteran
•	Fiduciary - Facility License**

**The documents listed below should be restricted**.  _We have requested that the VBMS document taxonomy is updated to reflect that the following fiduciary document types are restricted, however this will not be implemented until the September 2017 VBMS release at the earliest._  

**•	Misuse - Referral to Office of Inspector General
•	Change of Address Fiduciary
•	Change of Address Beneficiary**

Respectfully,

Kathel

**Comment by nicholasholtz** [comment] 2017-04-26 21:29
@aroltsch That list that Kathel confirmed corresponds with the [numbers above](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/450#issuecomment-297449722).

**Comment by kierachell** [comment] 2017-04-26 22:01
Thank you Nicholas! Let's just follow what they got for now and treat that email as the source of truth (put it in the code as a comment even). Let them figure out consistency later.

**Comment by aroltsch** [comment] 2017-04-27 11:40
Wonderful! Thanks Nicholas!

**Comment by aroltsch** [comment] 2017-04-27 11:44
I created a follow up issue, closing this!!!

**Closed by aroltsch** 2017-04-27 11:45 UTC
Labels: blocked, bug-medium-priority, foxtrot, In Progress
