### ISSUE TITLE
Errno::ECONNRESET

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow-efolder#590] opened 2017-08-09 21:02 UTC
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/348/activity/

Maybe we should just be catching errors here.

**Comment by aroltsch** [comment] 2017-11-06 19:03
Duplicate of https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/681

**Closed by aroltsch** 2017-11-06 19:03 UTC
